### ISSUE TITLE
Maintaining codebase by reducing styles using class and CSS custom properties

### ISSUE THREAD

**Issue by zannain** [AndrewHearnden/f1-3-c2p1-colmar-academy#4]
Avoid [combining](https://github.com/AndrewHearnden/f1-3-c2p1-colmar-academy/blob/master/Capstone%20Colmar/Resources/CSS/stylesheet.css#L79-L82) element selectors with class or id selectors. This is generally not considered [best practice](https://google.github.io/styleguide/htmlcssguide.html#Type_Selectors) and a better alternative is to just use an `id` instead if its a unique style. 

If it's a common style you can create a specific class for that style and call it in in the HTML

```css
.pd-10 {
   padding: 10px;
}
```

```html
<div class="pd-10">
    <p>Hello World</p>
</div>
<div class="pd-10">
    <p>Bye World</p>
</div>
```

This is actually how CSS frameworks such as [Bootstrap](https://getbootstrap.com/) work!

New to CSS3 are [CSS variables](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables). These make it much easier to update a style found in several elements at once because there is no need to do a search for every element that has a certain style. 

```css
:root {
    --font-size: 1.75rem;
    --font-weight: bold;
}

h1 {
     font-size: var(--font-size);
}

.className {
    font-weight: var(--font-weight);
}
```
